NSEDashboard/Models/Candalchart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NSEDashboard.Models
{
    public class Candalchart
    {        
        public double close { get; set; }
        public double low { get; set; }
        public double high { get; set; }
        public double open { get; set; }
        public double volume { get; set; }
        public double quantity { get; set; }
        public string date { get; set; }
    }
}

NSEDashboard/Models/FOData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NSEDashboard.Models
{
    public class FOData
    {
        public string INSTRUMENT { get; set; }
        public string SYMBOL { get; set; }
        public string EXP_DATE { get; set; }
        public string OPT_TYPE { get; set; }
        public double STR_PRICE { get; set; }
        public double OPEN_PRICE { get; set; }
        public double HI_PRICE { get; set; }
        public double LO_PRICE { get; set; }
        public double CLOSE_PRICE { get; set; }
        public double OPEN_Int { get; set; }
        public double TRD_QTY { get; set; }
         public double NO_OF_CONT { get; set; }
        public double NO_OF_TRADE { get; set; }
        public double NOTION_VAL { get; set; }
        public double PR_VA { get; set; }

      
    }
}

NSEDashboard/Models/FOModelData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NSEDashboard.Models
{
    public class FOModelData
    {
        public List<FOData> lstDate0 { get; set; }
        public List<FOData> lstDate1 { get; set; }
        public List<FOData> lstDate2 { get; set; }
        public List<FOData> lstDate3 { get; set; }
        public List<FOData> lstDate4 { get; set; }
        public List<FOData> lstDate5 { get; set; }
     
        public List<string> lastFiveDates { get; set; }
    }
}

NSEDashboard/Models/FoInputModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NSEDashboard.Models
{
    public class FoInputModel
    {
        public string SYMBOL { get; set; }
        public string EXP_DATE { get; set; }
        public string OPT_TYPE { get; set; }
        public string STR_PRICE { get; set; }
    }
}

NSEDashboard/Models/NSEInput.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NSEDashboard.Models
{
    public class NSEInput
    {
        public string name { get; set; }
        public string fullname { get; set; }
        public string high52 { get; set; }
        public string low52 { get; set; }
        public string trades { get; set; }
        public string gainer_losser { get; set; }
        public string gainRs { get; set; }
        public string gainPer { get; set; }
        public string cDate1 { get; set; }
        public string cDate2 { get; set; }

    }

    public class FOInput
    {
        public string name { get; set; }
        public string index { get; set; }
        public string date { get; set; }
        public string type { get; set; }
    }

    }

NSEDashboard/Models/PDData.cs
namespace NSEDashboard.Models
{
    public class PDData
    {
        public string Top_Avg_20 { get; set; }
        public string Purpose { get; set; }
        public string Ex_date { get; set; }
        public string MKT{get; set;}
      public string SERIES{get; set;}
      public string SYMBOL{get; set;}
      public string SECURITY{get; set;}
      public double PREV_CLOSE{get; set;}
      public double OPEN_PRICE{get; set;}
      public double HIGH_PRICE{get; set;}
      public double LOW_PRICE{get; set;}
      public double CLOSE_PRICE{get; set;}
      public double NET_TRDVAL{get; set;}
      public double NET_TRDQTY{get; set;}
      public string IND_SEC{get; set;}
      public string CORP_IND{get; set;}
      public long TRADES{get; set;}
      public double HI_52_WK{get; set;}
      public double LO_52_WK{get; set;}
      public double NET_PD{get; set;}
    }
}

NSEDashboard/Models/PDInputModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NSEDashboard.Models
{
    public class PDInputModel
    {
        public string name { get; set; }
        public string fullname { get; set; }
        public List<string > dates { get; set; }
    }
}

NSEDashboard/Models/PDModelData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NSEDashboard.Models
{
    public class PDModelData
    {
        public List<PDData> lstDate0 { get; set; }
        public List<PDData> lstDate1 { get; set; }
        public List<PDData> lstDate2 { get; set; }
        public List<PDData> lstDate3 { get; set; }
        public List<PDData>  lstDate4 { get; set; }
        public List<PDData> lstDate5 { get; set; }
        public List<PDData> lstDate6 { get; set; }    
        public List<PDData> lstDate7 { get; set; }

        public List<string> sectorInfo { get; set; }

        public List<string> lastFiveDates { get; set; }
    }
}

NSEDashboard/Models/UploadData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NSEDashboard.Models
{
    public class UploadData
    {
        public string uploadId { get; set; }
        public string uploadPath { get; set; }
        public string uploadDate { get; set; }

    }
}

NSEDashboard/Controllers/DashboardEQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NSEDashboard.Controllers
{
    public class DashboardEQController : Controller
    {
        // GET: Upload1
        public ActionResult Index()
        {
            return View();
        }
    }
}

NSEDashboard/Controllers/DashboardFOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NSEDashboard.Controllers
{
    public class DashboardFOController : Controller
    {
        // GET: DashboardFO
        public ActionResult Index()
        {
            return View();
        }
    }
}

NSEDashboard/Controllers/NSEClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NSEDashboard.Controllers
{
    public class NSEClientController : Controller
    {
        // GET: NSEClient
        public ActionResult Index()
        {
            return View();
        }


    }
}

NSEDashboard/Controllers/NSEDashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NSEDashboard.Controllers
{
    public class NSEDashboardController : Controller
    {
        // GET: NSEDashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

NSEDashboard/Controllers/UploadFilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NSEDashboard.Controllers
{
    public class UploadFilesController : Controller
    {
        // GET: UploadFiles
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index1()
        {
            return View();
        }


    }
}

NSEDashboard/Views/DashboardFO/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_NSEMasterPage.cshtml";
}

<div id="main" ng-app="app" ng-controller="FODashboard" style="margin-top:0px;padding-top:0px;overflow-y:hidden" ng-init="intiilizeCommon();">


    <!-- //breadcrumb-->

    <div id="content" style="margin-top:0px">
        <div class="row">
            <section class="panel">

                <div id="chart" class="with-3d-shadow with-transitions" style="float:left;overflow-x:auto;background:white;width:34%;border:1px solid  #ddd;margin-left:20px;">
                    <nvd3 data="data" options="options"></nvd3>
                </div>

                <div id="chart" class="with-3d-shadow with-transitions" style="float:left;overflow-x:auto;background:white;width:30%;border:1px solid  #ddd;margin-left:10px;">
                    <nvd3 data="data1" options="options1"></nvd3>
                </div>

                <div id="chart" class="with-3d-shadow with-transitions" style="overflow-x:auto;background:white;width:30%;border:1px solid  #ddd;margin-left:740px;">
                    <nvd3 data="data2" options="options1"></nvd3>
                </div>

                <div class="panel-body">
                    <div class="panel-group" id="accordion" style="margin-bottom:10px">
                        <div class="panel panel-default">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" style="padding:0px;">

                                <table class="table table-bordered" style="margin-bottom:0px !important;">
                                    <thead>
                                        <tr>

                                            <th colspan="3" style="width:17%">Filter</th>
                                            <th colspan="3" style="width:16%;text-align:center">{{lastdate[0]}}</th>

                                            <th colspan="3" style="width:15%;text-align:center;">{{lastdate[1]}}</th>

                                            <th colspan="3" style="width:13%;text-align:center;">{{lastdate[2]}}</th>

                                            <th colspan="3" style="width:14%;text-align:center;">{{lastdate[3]}}</th>

                                            <th colspan="3" style="width:15%;text-align:center;">{{lastdate[4]}}</th>
                                            <th ng-title="{{param.cDate1}}" style="text-align:center">D1</th>
                                            <th ng-title="{{param.cDate2}}" style="text-align:center">D2</th>

                                        </tr>
                                    </thead>
                                </table>
                            </a>
                            @*<div class="panel-heading" style="border: 1px solid  #ddd;padding-top:0px;padding-bottom:0px;">






                </div>*@
                            <div id="collapse1" class="panel-collapse collapse " style="border: 1px solid #ddd;border-top: none;">
                                <div class="panel-body">
                                    <div class="col-xs-12">
                                        <div class="col-xs-3">
                                            <div class="form-group">
                                                <label class="control-label col-md-3" style="text-align: left;">Name</label>
                                                <div class="col-md-9">
                                                    <input type="text" class="form-control" ng-model="param.name">
                                                    
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-xs-3">
                                            <div class="form-group">
                                                <label class="control-label col-md-3" style="text-align: left;">Index</label>
                                                <div class="col-md-9">
                                                    <input type="text" class="form-control" ng-model="param.index">
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-xs-3">
                                            <div class="form-group">
                                                <label class="control-label col-md-3" style="text-align: left;">Date</label>
                                                <div class="col-md-9">
                                                    <input type="text" class="form-control" ng-model="param.date">
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-xs-3">
                                            <div class="form-group">
                                                <label class="control-label col-md-3" style="text-align: left;">Type</label>
                                                <div class="col-md-9">
                                                    <input type="text" class="form-control" ng-model="param.type">
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-xs-3">
                                            <button type="submit" class="btn btn-theme" ng-click="Apply();">Apply</button>
                                        </div>

                                    </div> </div>
                            </div>


                        </div>

                    </div>

                    <div class="table-responsive" style="height:375px;overflow-y:auto;overflow-x:hidden;margin-top:0px;">
                        <loading></loading>
                        <div id="message" style="padding-top:5px;"></div>
                        <table class="table table-bordered" style="font-size:11px;">

                            <tbody align="center" style="color:black">


                                <tr ng-repeat="item in resultset track by $index">


                                    <td style="padding:1px;text-align:left;background-color: rgb(0, 255, 255);" ng-if="item.set=='false'"><button ng-click="bindCandle(item);">{{item.Symbol}}</button></td>
                                    <td style="padding:1px;background-color:rgb(254, 249, 231)" ng-if="item.set=='false'">{{item.Ex_date}}</td>
                                    <td style="padding:1px;background-color:rgb(254, 249, 231)" ng-if="item.set=='false'">{{item.StrPrice}}</td>
                                    <td style="padding:1px;" ng-if="item.set=='false'">{{item.Opt}}</td>
                                   
                                    <td style="padding:1px;background-color: rgb(0, 255, 128);color:black;border-right:3px solid #898989;" ng-if="item.set=='false'">{{item.d1}}</td>

                                    <td style="padding:1px;background-color: rgb(196, 244, 243); color:green;" ng-if="item.set=='false' && item.d2>0">{{item.d2}}</td>
                                    <td style="padding:1px;background-color: rgb(196, 244, 243);color:red;" ng-if="item.set=='false' && item.d2<=0">{{item.d2}}</td>
                                    <td style="padding:1px;background-color: rgb(188, 192, 245);" ng-if="item.set=='false'">{{item.d3}}</td>
                                    <td style="padding:1px;background-color: rgb(233, 231, 167);border-right:3px solid #898989;" ng-if="item.set=='false'">{{item.d4}}</td>

                                    <td style="padding:1px;background-color: rgb(196, 244, 243); color:green;" ng-if="item.set=='false' && item.d5>0">{{item.d5}}</td>
                                    <td style="padding:1px;background-color: rgb(196, 244, 243);color:red;" ng-if="item.set=='false' && item.d5<=0">{{item.d5}}</td>
                                    <td style="padding:1px;background-color: rgb(188, 192, 245);" ng-if="item.set=='false'">{{item.d6}}</td>
                                    <td style="padding:1px;background-color: rgb(233, 231, 167);border-right:3px solid #898989;" ng-if="item.set=='false'">{{item.d7}}</td>

                                    <td style="padding:1px;background-color: rgb(196, 244, 243); color:green;" ng-if="item.set=='false' && item.d8>0">{{item.d8}}</td>
                                    <td style="padding:1px;background-color: rgb(196, 244, 243);color:red;" ng-if="item.set=='false' && item.d8<=0">{{item.d8}}</td>
                                    <td style="padding:1px;background-color: rgb(188, 192, 245);" ng-if="item.set=='false'">{{item.d9}}</td>
                                    <td style="padding:1px;background-color: rgb(233, 231, 167);border-right:3px solid #898989;" ng-if="item.set=='false'">{{item.d10}}</td>

                                    <td style="padding:1px;background-color: rgb(196, 244, 243); color:green;" ng-if="item.set=='false' && item.d11>0">{{item.d11}}</td>
                                    <td style="padding:1px;background-color: rgb(196, 244, 243);color:red;" ng-if="item.set=='false' && item.d11<=0">{{item.d11}}</td>
                                    <td style="padding:1px;background-color: rgb(188, 192, 245);" ng-if="item.set=='false'">{{item.d12}}</td>
                                    <td style="padding:1px;background-color: rgb(233, 231, 167);border-right:3px solid #898989;" ng-if="item.set=='false'">{{item.d13}}</td>


                                    <td style="padding:1px;background-color: rgb(196, 244, 243); color:green;" ng-if="item.set=='false' && item.d14>0">{{item.d14}}</td>
                                    <td style="padding:1px;background-color: rgb(196, 244, 243);color:red;" ng-if="item.set=='false' && item.d14<=0">{{item.d14}}</td>
                                    <td style="padding:1px;background-color: rgb(188, 192, 245);" ng-if="item.set=='false'">{{item.d15}}</td>
                                    <td style="padding:1px;background-color: rgb(233, 231, 167);border-right:3px solid #898989;" ng-if="item.set=='false'">{{item.d16}}</td>

                                 

                                    <td style="padding:1px;text-align:left;background-color: rgb(255, 255, 128);" ng-if="item.set=='true'">{{item.Symbol}}</td>
                                    <td style="padding:1px;background-color:rgb(254, 249, 231)" ng-if="item.set=='true'">{{item.Ex_date}}</td>
                                    <td style="padding:1px;" ng-if="item.set=='true'"></td>
                                    <td style="padding:1px;" ng-if="item.set=='true'"></td>
                                    <td style="padding:1px;background-color: rgb(215, 30, 77);color:white;border-right:3px solid #898989;" ng-if="item.set=='true'">{{item.d1}}</td>

                                    <td style="padding:1px;background-color: rgb(242, 183, 247);" ng-if="item.set=='true'">{{item.d2}}</td>
                                    <td style="padding:1px;background-color: rgb(204, 226, 158);" ng-if="item.set=='true'">{{item.d3}}</td>
                                    <td style="padding:1px;background-color: rgb(188, 192, 245);border-right:3px solid #898989;" ng-if="item.set=='true'">{{item.d4}}</td>

                                    <td style="padding:1px;background-color: rgb(242, 183, 247);" ng-if="item.set=='true'">{{item.d5}}</td>
                                    <td style="padding:1px;background-color: rgb(204, 226, 158);" ng-if="item.set=='true'">{{item.d6}}</td>
                                    <td style="padding:1px;background-color: rgb(188, 192, 245);border-right:3px solid #898989;" ng-if="item.set=='true'">{{item.d7}}</td>

                                    <td style="padding:1px;background-color: rgb(242, 183, 247);" ng-if="item.set=='true'">{{item.d8}}</td>
                                    <td style="padding:1px;background-color: rgb(204, 226, 158);" ng-if="item.set=='true'">{{item.d9}}</td>
                                    <td style="padding:1px;background-color: rgb(188, 192, 245);border-right:3px solid #898989;" ng-if="item.set=='true'">{{item.d10}}</td>

                                    <td style="padding:1px;background-color: rgb(242, 183, 247);" ng-if="item.set=='true'">{{item.d11}}</td>
                                    <td style="padding:1px;background-color: rgb(204, 226, 158);" ng-if="item.set=='true'">{{item.d12}}</td>
                                    <td style="padding:1px;background-color: rgb(188, 192, 245);border-right:3px solid #898989;" ng-if="item.set=='true'">{{item.d13}}</td>

                                    <td style="padding:1px;background-color: rgb(242, 183, 247);" ng-if="item.set=='true'">{{item.d14}}</td>
                                    <td style="padding:1px;background-color: rgb(204, 226, 158);" ng-if="item.set=='true'">{{item.d15}}</td>
                                    <td style="padding:1px;background-color: rgb(188, 192, 245);border-right:3px solid #898989;" ng-if="item.set=='true'">{{item.d16}}</td>

                                   

                                </tr>


                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
        </div>
        <!-- //content > row-->
    </div>
    
</div>

NSEDashboard/Views/Shared/_NSEMasterPage.cshtml
<!DOCTYPE html>

<html>
<head>

    <!-- Meta information -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    <!-- Title-->
    <title>NSE Dashboard</title>

    <!-- Favicons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="~/assets/ico/favicon.ico">

    <!-- CSS Stylesheet-->
    <link type="text/css" rel="stylesheet" href="~/assets/css/bootstrap/bootstrap.min.css" />
    <link type="text/css" rel="stylesheet" href="~/assets/css/bootstrap/bootstrap-themes.css" />
    <link rel="stylesheet" href="~/bower_components/bootswatch/bootstrap.css" media="screen">
    <link rel="stylesheet" href="~/bower_components/bootswatch/bootswatch.min.css">
    <link rel="stylesheet" href="~/bower_components/json-tree/json-tree.css">
    <link rel="stylesheet" href="~/bower_components/nvd3/build/nv.d3.css">
    <link rel="stylesheet" href="~/bower_components/angular-gridster/dist/angular-gridster.min.css">
    <!--<link rel="stylesheet" href="http://yandex.st/highlightjs/8.0/styles/rainbow.min.css">-->

    <link href="~/bower_components/rainbow.min.css" rel="stylesheet" />
    <link href="~/bower_components/style.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="css/main.css">
        <link rel="stylesheet" href="pages/gridster/style.css">*@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="~/assets/css/style.css" />

    <!-- Styleswitch if  you don't chang theme , you can delete -->
    <link type="text/css" rel="alternate stylesheet" media="screen" title="style1" href="~/assets/css/styleTheme1.css" />
    <link type="text/css" rel="alternate stylesheet" media="screen" title="style2" href="~/assets/css/styleTheme2.css" />
    <link type="text/css" rel="alternate stylesheet" media="screen" title="style3" href="~/assets/css/styleTheme3.css" />
    <link type="text/css" rel="alternate stylesheet" media="screen" title="style4" href="~/assets/css/styleTheme4.css" />

    <style type="text/css">

        a {
  color: #900;
  text-decoration: none;
}

a:hover {
  color: red;
  position: relative;
}

      
a[title]:hover:after {
  content: attr(title);
  padding: 4px 8px;
  color: #333;
  position: absolute;
  left: 0;
  top: 100%;
  white-space: nowrap;
  z-index: 20px;
  -moz-border-radius: 5px;
  -webkit-border-radius: 5px;
  border-radius: 5px;
  -moz-box-shadow: 0px 0px 4px #222;
  -webkit-box-shadow: 0px 0px 4px #222;
  box-shadow: 0px 0px 4px #222;
  background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);
  background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #eeeeee),color-stop(1, #cccccc));
  background-image: -webkit-linear-gradient(top, #eeeeee, #cccccc);
  background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);
  background-image: -ms-linear-gradient(top, #eeeeee, #cccccc);
  background-image: -o-linear-gradient(top, #eeeeee, #cccccc);
}

    </style>
   

</head>
<body class="leftMenu nav-collapse in">
    <div id="wrapper" style="margin-top:0px">
    
     
        @RenderBody()
     
        <!--
        //////////////////////////////////////////////////////////////
        //////////     LEFT NAV MENU     //////////
        ///////////////////////////////////////////////////////////
        -->
        <nav id="menu" data-search="close">
            <ul>
                
                <li>
                    <span> <i class="icon fa  fa fa-rocket"></i>  @Html.ActionLink("EQ Dashboard", "Index", "DashboardEQ")</span>
                </li>

                <li>
                    <span> <i class="icon fa  fa fa-rocket"></i>  @Html.ActionLink("Options Dashboard", "Index", "DashboardFO")</span>
                </li>
                <li>
                    <span> <i class="icon fa fa-file-text"></i>  @Html.ActionLink("Upload Files", "Index", "UploadFiles")</span> 
                </li>
               
             
                
            </ul>
        </nav>
      

    </div>
    <!-- //wrapper-->
    <!--
    ////////////////////////////////////////////////////////////////////////
    //////////     JAVASCRIPT  LIBRARY     //////////
    /////////////////////////////////////////////////////////////////////
    -->
    <!-- Jquery Library -->
    <script type="text/javascript" src="~/assets/js/jquery.min.js"></script>
    <script type="text/javascript" src="~/assets/js/jquery.ui.min.js"></script>
    @*<script src="lib/highlight.pack.js"></script>*@
    <script src="~/bower_components/highlight.pack.js"></script>
    <script type="text/javascript" src="~/assets/plugins/bootstrap/bootstrap.min.js"></script>




   

    <!-- Modernizr Library For HTML5 And CSS3 -->
    <script type="text/javascript" src="~/assets/js/modernizr/modernizr.js"></script>
    <script type="text/javascript" src="~/assets/plugins/mmenu/jquery.mmenu.js"></script>
    <script type="text/javascript" src="~/assets/js/styleswitch.js"></script>
    <!-- Library 10+ Form plugins-->
    <script type="text/javascript" src="~/assets/plugins/form/form.js"></script>
    <!-- Datetime plugins -->
    <script type="text/javascript" src="~/assets/plugins/datetime/datetime.js"></script>
    <!-- Library Chart-->
    <script type="text/javascript" src="~/assets/plugins/chart/chart.js"></script>
    <!-- Library  5+ plugins for bootstrap -->
    <script type="text/javascript" src="~/assets/plugins/pluginsForBS/pluginsForBS.js"></script>
    <!-- Library 10+ miscellaneous plugins -->
    <script type="text/javascript" src="~/assets/plugins/miscellaneous/miscellaneous.js"></script>
    <!-- Library Themes Customize-->
    <script type="text/javascript" src="~/assets/js/caplet.custom.js"></script>
    <!-- Library jqvmap -->
    <script src="~/assets/plugins/vmap/jquery.vmap.js" type="text/javascript"></script>
    <script src="~/assets/plugins/vmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
    <script src="~/assets/plugins/vmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>
    <!-- Library Owl Carousel  -->
    <script type="text/javascript" src="~/assets/plugins/owl-carousel/owl.carousel.js"></script>
    <link href="~/assets/plugins/owl-carousel/owl.carousel.css" rel="stylesheet">
    <link href="~/assets/plugins/owl-carousel/owl.theme.css" rel="stylesheet">
    <link href="~/assets/plugins/owl-carousel/owl.transitions.css" rel="stylesheet">
    <!-- Library datable -->
    <script type="text/javascript" src="~/assets/plugins/datable/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/assets/plugins/datable/dataTables.bootstrap.js"></script>

    <!-- Angular -->
    @*<script src="~/vendor_components/angular/angular.js"></script>
    <script src="~/vendor_components/angular-route/angular-route.js"></script>*@
  

    <script src="~/bower_components/bootswatch/bootswatch.js"></script>
    <script src="~/bower_components/angular/angular.min.js"></script>
    <script src="~/bower_components/angular-route/angular-route.min.js"></script>
    <script src="~/bower_components/d3/d3.min.js"></script>
    <script src="~/bower_components/angular-nvd3/dist/angular-nvd3.js"></script>
    
    <script src="~/bower_components/json-tree/json-tree.js"></script>
    <script src="~/bower_components/nvd3/build/nv.d3.js"></script>
    <script src="~/bower_components/angular-gridster/dist/angular-gridster.min.js"></script>
    <script src="~/bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
    <script src="~/App_Js/AppStart.js"></script>
    <script src="~/App_Js/controllers/HomeController.js"></script>
    <script src="~/App_Js/controllers/DashboardController.js"></script>
    <script src="~/App_Js/controllers/FODashboardController.js"></script>
    
    <script type="text/javascript">
	jQuery(document).ready(function() {
		jQuery('#vmap').vectorMap({
			map: 'world_en',
			backgroundColor: '#736086',
			color: '#ffffff',
			hoverOpacity: 0.7,
			selectedColor: '#666666',
			enableZoom: true,
			showTooltip: true,
			values: sample_data,
			scaleColors: ["#0aa699", "#0bbeaf"],
			normalizeFunction: 'polynomial'
		});
		$("#owl-demo").owlCarousel({
			autoPlay : 5000,
			stopOnHover : true,
			paginationSpeed : 5000,
			goToFirstSpeed : 3000,
			singleItem : true,
			autoHeight : true,
			transitionStyle:"fade"
		});
		$('table[data-provide="data-table"]').dataTable({
			"iDisplayLength": 5
		});
	});
    </script>
</body>
</html>